INCLUDE="spacemit-k1"
BOARD_NAME="ky-x1"

TAG="k1-bl-v2.1-release"

U_BOOT_REPO="https://github.com/orangepi-xunlong/u-boot-orangepi.git"
U_BOOT_TAG="v2022.10-ky"
U_BOOT_DEFCONFIG="x1_defconfig"
U_BOOT_MAKE_FLAGS="OPENSBI=/build/opensbi/build/platform/generic/firmware/fw_dynamic.bin"

KERNEL_REPO="https://github.com/OctopusET/linux-k1-x1.git"
KERNEL_TAG="orange-pi-6.6-ky"
KERNEL_DEFCONFIG="x1_defconfig"
BOARD_DTB_GLOB="arch/riscv/boot/dts/ky/*.dtb"

# Boot environment
BOOT_ROOT_DEV="/dev/mmcblk0p2"
BOOT_KERNEL_NAME="Image"
BOOT_SERIAL_TTY="ttyS0"
