BOARD_NAME="ky-x1"
BOARD_ARCH="riscv64"
BOARD_CFLAGS="-O3 -march=rv64gcv_zvl256b -pipe"
SYSROOT="rv64gcv_zvl256b"
CROSS_COMPILE="riscv64-unknown-linux-gnu-"
KERNEL_ARCH="riscv"

TAG="k1-bl-v2.1-release"
OPENSBI_TAG="k1-opensbi"
OPENSBI_REPO="https://github.com/cyyself/opensbi"
OPENSBI_PLATFORM="generic"
OPENSBI_MAKE_FLAGS="LLVM=1 PLATFORM_DEFCONFIG=defconfig"
U_BOOT_MAKE_FLAGS="OPENSBI=/build/opensbi/build/platform/generic/firmware/fw_dynamic.bin"
U_BOOT_REPO="https://github.com/orangepi-xunlong/u-boot-orangepi.git"
U_BOOT_TAG="v2022.10-ky"
U_BOOT_DEFCONFIG="x1_defconfig"
KERNEL_REPO="https://github.com/OctopusET/linux-k1-x1.git"
KERNEL_TAG="orange-pi-6.6-ky"
KERNEL_DEFCONFIG="x1_defconfig"
FIRMWARE_REPO="https://gitee.com/bianbu-linux/buildroot-ext.git"

BOARD_DTB_GLOB="arch/riscv/boot/dts/ky/*.dtb"
BOARD_FIRMWARE_OVERLAY="board/spacemit/k1/target_overlay/lib/firmware"
HOST_FIRMWARE_PATHS=("/lib/firmware/rtw89")
DRACUT_MODULES="busybox"
BOOT_KERNEL_NAME="Image"

# Boot environment
BOOT_ROOT_DEV="/dev/mmcblk0p2"
BOOT_CONSOLE="ttyS0,115200"
BOOT_HOSTNAME="gentoo"
BOOT_SERIAL_TTY="ttyS0"
BOOT_SERIAL_BAUD="115200"

BUILD_STEPS=(deps checkout bootloader kernel assemble pack)

BOOT_SERVICES=("sshd:default" "metalog:default" "ntp-client:default")
