BOARD_NAME="k1"
BOARD_ARCH="riscv64"
BOARD_CFLAGS="-O3 -march=rv64gcv_zvl256b -pipe"
SYSROOT="rv64gcv_zvl256b"
CROSS_COMPILE="riscv64-unknown-linux-gnu-"
KERNEL_ARCH="riscv"

TAG="k1-bl-v2.2.7-release"
OPENSBI_TAG="k1-opensbi"
OPENSBI_REPO="https://github.com/cyyself/opensbi"
OPENSBI_PLATFORM="generic"
U_BOOT_REPO="https://gitee.com/bianbu-linux/uboot-2022.10.git"
U_BOOT_DEFCONFIG="k1_defconfig"
FIRMWARE_REPO="https://gitee.com/bianbu-linux/buildroot-ext.git"
KERNEL_REPO="https://gitee.com/bianbu-linux/linux-6.6.git"
KERNEL_DEFCONFIG="k1_defconfig"

BOARD_DTB_GLOB="arch/riscv/boot/dts/spacemit/*.dtb"
BOARD_FIRMWARE_OVERLAY="board/spacemit/k1/target_overlay/lib/firmware"
HOST_FIRMWARE_PATHS=("/lib/firmware/rtw89")
DRACUT_MODULES="busybox"

# Boot environment
BOOT_ROOT_DEV="/dev/mmcblk0p6"
BOOT_CONSOLE="ttyS0,115200"
BOOT_LOGLEVEL="8"
BOOT_KERNEL_NAME="Image.gz.itb"
BOOT_RAMDISK_NAME="initramfs.img"

# Services to enable (service:runlevel pairs)
BUILD_STEPS=(deps checkout bootloader kernel assemble pack)

BOOT_SERVICES=("sshd:default" "metalog:default" "ntp-client:default")
BOOT_HOSTNAME="gentoo"
BOOT_SERIAL_TTY="console"
BOOT_SERIAL_BAUD="115200"
